title: IBM watsonx.ai
description: Java SDK for watsonx.ai
watsonx_version: "0.18.0"
theme: just-the-docs
markdown: kramdown
permalink: pretty
logo: "/assets/images/ibm-logo.svg"
favicon_ico: "/assets/images/favicon.ico"

# Just the Docs configuration
color_scheme: nil # Use custom Carbon styling
search_enabled: true
search_tokenizer_separator: /[\s/]+/
nav_sort: case_insensitive
heading_anchors: true
aux_links_new_tab: true
footer_content: "Copyright 2025 IBM Corporation. Licensed under the Apache License 2.0."
back_to_top: true
back_to_top_text: "Back to top"
aux_links:
  "GitHub":
    - "https://github.com/IBM/watsonx-ai-java-sdk"

nav_enabled: true
toc:
  enabled: true
  min_level: 2
  max_level: 4
